spring:
  application:
    name: eureka-client
server:
  port: 8763
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 15
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
